name: Build Geode Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-2022
          - name: Android
            os: ubuntu-latest
            target: Android

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar e Instalar Geode CLI
        uses: geode-sdk/actions/setup@main
        with:
          build-config: Release
          target: ${{ matrix.config.target }}

      - name: Compilar Mod Completo
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
